# Preprocessing:

first we need to do

    - Outlier Detection
    - Train Test Split

## Import the libraries

In [11]:
import sys, os
import polars as pl
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split





sys.path.append(os.path.join(os.getcwd(), "Utils"))
BASE_DIR = os.path.abspath("..")
sys.path.append(os.path.join(BASE_DIR, "utils"))


from StatMelt import iqr_bounds

## Outlier Detection:
- in the EDA section We found out that there is no outliers in my dataset
- there is no Missing values in this dataset.

In [12]:
df = pd.read_csv('../Data/Left/LeftFinal.csv')
df.head()

   Unnamed: 0  day        date time_of_day  Diastolic  Systolic  Pulse
0           0  1.0  1405-02-08       night       69.0     138.0   62.0
1           1  1.0  1405-02-08        noon       74.0     140.0   83.0
2           2  1.0  1405-02-08     morning       89.0     149.0   65.0
3           3  2.0  1405-02-09       night       75.0     137.0   69.0
4           4  2.0  1405-02-09        noon       75.0     141.0   64.0

In [13]:
iqr_bounds(df['Diastolic'])

(np.float64(62.5), np.float64(82.5), np.float64(5.0))

## Train Test Split
- Because this is a time series dataset and I want to do Time series Analysis on this data then I should just get the values from the last 20% of the dataset as the test set.

- I need to drop the columns that are not useful.
    - the first column is `day` because it will surve no purpose to be in My Time series Analysis.
    - the second column is `Pulse` because from EDA I found out that it has near Zero correlation to Diastolic and Systolic
    - I am not sure about what should I set as the target variable, My gut feeling says Diastolic, I will change it to Systolic and find how that variable response.

In [14]:
df = df.drop(columns=['Unnamed: 0','day','Pulse'])
df['date'] = pd.to_datetime(df['date'])
df.set_index('date')

           time_of_day  Diastolic  Systolic
date
1405-02-08       night       69.0     138.0
1405-02-08        noon       74.0     140.0
1405-02-08     morning       89.0     149.0
1405-02-09       night       75.0     137.0
1405-02-09        noon       75.0     141.0
1405-02-09     morning       78.0     151.0
1405-02-10        noon       66.0     113.0
1405-02-10       night       77.0     138.0
1405-02-10     morning       83.0     127.0
1405-02-11     morning       75.0     128.0
1405-02-11        noon       74.0     141.0
1405-02-11       night       85.0     139.0
1405-02-12     morning       74.0     143.0
1405-02-12        noon       66.0     125.0
1405-02-12       night       74.0     131.0
1405-02-13        noon       72.0     131.0
1405-02-13       night       75.0     143.0
1405-02-13     morning       68.0     123.0
1405-02-14       night       68.0     127.0
1405-02-14        noon       74.0     132.0
1405-02-14     morning       73.0     111.0
1405-02-15     morning       86.0     123.0
1405-02-15       night       75.0     133.0
1405-02-15        noon       65.0     129.0
1405-02-16     morning       70.0     123.0
1405-02-16        noon       71.0     125.0
1405-02-16       night       84.0     122.0
1405-02-17        noon       63.0     122.0
1405-02-17       night       70.0     123.0
1405-02-17     morning       73.0     133.0

In [15]:
df.info()
df

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         30 non-null     datetime64[us]
 1   time_of_day  30 non-null     str
 2   Diastolic    30 non-null     float64
 3   Systolic     30 non-null     float64
dtypes: datetime64[us](1), float64(2), str(1)
memory usage: 1.1 KB

         date time_of_day  Diastolic  Systolic
0  1405-02-08       night       69.0     138.0
1  1405-02-08        noon       74.0     140.0
2  1405-02-08     morning       89.0     149.0
3  1405-02-09       night       75.0     137.0
4  1405-02-09        noon       75.0     141.0
5  1405-02-09     morning       78.0     151.0
6  1405-02-10        noon       66.0     113.0
7  1405-02-10       night       77.0     138.0
8  1405-02-10     morning       83.0     127.0
9  1405-02-11     morning       75.0     128.0
10 1405-02-11        noon       74.0     141.0
11 1405-02-11       night       85.0     139.0
12 1405-02-12     morning       74.0     143.0
13 1405-02-12        noon       66.0     125.0
14 1405-02-12       night       74.0     131.0
15 1405-02-13        noon       72.0     131.0
16 1405-02-13       night       75.0     143.0
17 1405-02-13     morning       68.0     123.0
18 1405-02-14       night       68.0     127.0
19 1405-02-14        noon       74.0     132.0
20 1405-02-14     morning       73.0     111.0
21 1405-02-15     morning       86.0     123.0
22 1405-02-15       night       75.0     133.0
23 1405-02-15        noon       65.0     129.0
24 1405-02-16     morning       70.0     123.0
25 1405-02-16        noon       71.0     125.0
26 1405-02-16       night       84.0     122.0
27 1405-02-17        noon       63.0     122.0
28 1405-02-17       night       70.0     123.0
29 1405-02-17     morning       73.0     133.0

In [16]:
X = df.drop(columns='Systolic')
y = df['Systolic']

In [ ]:
name_change = {
    'morning':0,
    'noon':1,
    'night':2
}
# there is a problem here first it shows night then noon then morning it can cause misunderstanding in plots
df['time_of_day'] = df['time_of_day'].map(name_change)