# Preprocessing:

first we need to do

    - Outlier Detection
    - Train Test Split

## Import the libraries

In [1]:
import sys, os
import polars as pl
import numpy as np
from sklearn.model_selection import train_test_split





sys.path.append(os.path.join(os.getcwd(), "Utils"))
BASE_DIR = os.path.abspath("..")
sys.path.append(os.path.join(BASE_DIR, "utils"))


from StatMelt import iqr_bounds

## Outlier Detection:
- in the EDA section We found out that there is no outliers in my dataset
- there is no Missing values in this dataset.

In [2]:
df = pl.read_csv('../Data/Left/LeftFinal.csv')
df.head()

shape: (5, 7)
┌─────┬─────┬────────────┬─────────────┬───────────┬──────────┬───────┐
│     ┆ day ┆ date       ┆ time_of_day ┆ Diastolic ┆ Systolic ┆ Pulse │
│ --- ┆ --- ┆ ---        ┆ ---         ┆ ---       ┆ ---      ┆ ---   │
│ i64 ┆ f64 ┆ str        ┆ str         ┆ f64       ┆ f64      ┆ f64   │
╞═════╪═════╪════════════╪═════════════╪═══════════╪══════════╪═══════╡
│ 0   ┆ 1.0 ┆ 1405-02-08 ┆ night       ┆ 69.0      ┆ 138.0    ┆ 62.0  │
│ 1   ┆ 1.0 ┆ 1405-02-08 ┆ noon        ┆ 74.0      ┆ 140.0    ┆ 83.0  │
│ 2   ┆ 1.0 ┆ 1405-02-08 ┆ morning     ┆ 89.0      ┆ 149.0    ┆ 65.0  │
│ 3   ┆ 2.0 ┆ 1405-02-09 ┆ night       ┆ 75.0      ┆ 137.0    ┆ 69.0  │
│ 4   ┆ 2.0 ┆ 1405-02-09 ┆ noon        ┆ 75.0      ┆ 141.0    ┆ 64.0  │
└─────┴─────┴────────────┴─────────────┴───────────┴──────────┴───────┘

In [3]:
iqr_bounds(df['Diastolic'])

(62.0, 86.0, 6.0)

## Train Test Split
- Because this is a time series dataset and I want to do Time series Analysis on this data then I should just get the values from the last 20% of the dataset as the test set.

- I need to drop the columns that are not useful.
    - the first column is `day` because it will surve no purpose to be in My Time series Analysis.
    - the second column is `Pulse` because from EDA I found out that it has near Zero correlation to Diastolic and Systolic
    - I am not sure about what should I set as the target variable, My gut feeling says Diastolic, I will change it to Systolic and find how that variable response.

In [7]:
# df = df.drop(['day','Pulse'])
df

shape: (27, 5)
┌─────┬────────────┬─────────────┬───────────┬──────────┐
│     ┆ date       ┆ time_of_day ┆ Diastolic ┆ Systolic │
│ --- ┆ ---        ┆ ---         ┆ ---       ┆ ---      │
│ i64 ┆ str        ┆ str         ┆ f64       ┆ f64      │
╞═════╪════════════╪═════════════╪═══════════╪══════════╡
│ 0   ┆ 1405-02-08 ┆ night       ┆ 69.0      ┆ 138.0    │
│ 1   ┆ 1405-02-08 ┆ noon        ┆ 74.0      ┆ 140.0    │
│ 2   ┆ 1405-02-08 ┆ morning     ┆ 89.0      ┆ 149.0    │
│ 3   ┆ 1405-02-09 ┆ night       ┆ 75.0      ┆ 137.0    │
│ 4   ┆ 1405-02-09 ┆ noon        ┆ 75.0      ┆ 141.0    │
│ …   ┆ …          ┆ …           ┆ …         ┆ …        │
│ 22  ┆ 1405-02-15 ┆ noon        ┆ 65.0      ┆ 129.0    │
│ 23  ┆ 1405-02-15 ┆ night       ┆ 75.0      ┆ 133.0    │
│ 24  ┆ 1405-02-16 ┆ noon        ┆ 71.0      ┆ 125.0    │
│ 25  ┆ 1405-02-16 ┆ night       ┆ 84.0      ┆ 122.0    │
│ 26  ┆ 1405-02-16 ┆ morning     ┆ 70.0      ┆ 123.0    │
└─────┴────────────┴─────────────┴───────────┴──────────┘

In [10]:
# df = df.with_columns(pl.col("date").str.to_date("%Y-%m-%d"))
df

shape: (27, 5)
┌─────┬────────────┬─────────────┬───────────┬──────────┐
│     ┆ date       ┆ time_of_day ┆ Diastolic ┆ Systolic │
│ --- ┆ ---        ┆ ---         ┆ ---       ┆ ---      │
│ i64 ┆ date       ┆ str         ┆ f64       ┆ f64      │
╞═════╪════════════╪═════════════╪═══════════╪══════════╡
│ 0   ┆ 1405-02-08 ┆ night       ┆ 69.0      ┆ 138.0    │
│ 1   ┆ 1405-02-08 ┆ noon        ┆ 74.0      ┆ 140.0    │
│ 2   ┆ 1405-02-08 ┆ morning     ┆ 89.0      ┆ 149.0    │
│ 3   ┆ 1405-02-09 ┆ night       ┆ 75.0      ┆ 137.0    │
│ 4   ┆ 1405-02-09 ┆ noon        ┆ 75.0      ┆ 141.0    │
│ …   ┆ …          ┆ …           ┆ …         ┆ …        │
│ 22  ┆ 1405-02-15 ┆ noon        ┆ 65.0      ┆ 129.0    │
│ 23  ┆ 1405-02-15 ┆ night       ┆ 75.0      ┆ 133.0    │
│ 24  ┆ 1405-02-16 ┆ noon        ┆ 71.0      ┆ 125.0    │
│ 25  ┆ 1405-02-16 ┆ night       ┆ 84.0      ┆ 122.0    │
│ 26  ┆ 1405-02-16 ┆ morning     ┆ 70.0      ┆ 123.0    │
└─────┴────────────┴─────────────┴───────────┴──────────┘